### ISSUE TITLE
How to install the module?

### ISSUE THREAD

**Issue by milanstojanov** [magento-hackathon/Hackathon_Blog#1]
Hi, 

Thanks for the module. As someone who is a complete beginner with Magento 2, this example will be a great starting point. However, I'd like to ask how would I go about adding this module to the existing Magento 2 codebase? Is it just a matter of copying and placing files into the project folder, or there's something I need to configure in order to pull this with composer? I was expecting to find more information in the project description :)

Thanks again, 
Milan

**Comment by vincenthornikx** [comment]
Hi Milan,

All you need to do is copy the files to your app/code directory. It should
then look like app/code/Hackathon/Blog/<files>.

Please note that we haven't implemented any adminhtml pages. Creating,
updating, and removing blog posts can be done through the rest api.

Kind regards,
Vincent

## 

Met vriendelijke groet,

Vincent Hornikx
Senior Magento Developer

Symfony B.V.
Kantoorpand LECTRIC Groep
Pr. Bernhardstraat 14
5211 HE Den Bosch

T. 073 - 850 72 62
E. v.hornikx@symfony.nl
W. http://www.symfony.nl

**Comment by SolsWebdesign** [comment]
Hi Milan,

It is very much a work-in-progress. If you have installed it, you should see an item "Hackathon blog" in the "Content" menu. Clicking on it will just say 'hi' for now. If you don't see it, refresh cache (by emptying the cache directory) and if you still don't see it, you may try adding 'Hackathon_Blog' => 1 to the config.php file under the app/etc directory. But it should work without.

Kind regards,
Isolde
